version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: feedbackdb
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/feedbackdb
      - GEMINI_PROVIDER=google
      - GEMINI_API_KEY=AIzaSyDuXve9WfpQ_YefCR8n43jkV2AMw8yZ2A8
      - GEMINI_MODEL=gemini-2.0-flash   
      - GEMINI_TIMEOUT=20

    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data:
